# Generated by Django 3.2.5 on 2021-07-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('mentor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ментор')),
                ('assistant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ассистент')),
                ('class_room', models.CharField(max_length=25, verbose_name='Аудитория')),
                ('start_date', models.DateField(verbose_name='Дата начала курса')),
                ('end_date', models.DateField(verbose_name='Дата окончания курса')),
                ('price', models.FloatField(verbose_name='Сумма')),
            ],
        ),
    ]
