# Generated by Django 3.2.5 on 2021-07-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(verbose_name='Azamat'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('pin', models.CharField(max_length=8, verbose_name='Пин')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.course', verbose_name='Курс')),
            ],
        ),
    ]
