# Generated by Django 3.2.5 on 2021-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.EmailField(max_length=254, verbose_name='Картинка'),
        ),
    ]
